using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Web;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace NREout.Models
{
    [Table("Usuario")]
    public class FuncionarioModel
    {

        /*
        public void Funcionario() {
            CriadoEm = DateTime.Now;
        }
        */
        [Key]
        public int? id { get; set; }



        [DisplayName("Nome Completo")]
        [StringLength(50, ErrorMessage = "O campo permite no máximo 50 caracteres!")]
        public string Nome { get; set; }   //nome do funcionario

        //[DisplayName("E-mail Pessoal")]
        //[StringLength(50)]
        //// [Required(ErrorMessage = "Informe o seu E-mail Pessoal.")]
        ////[RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*", ErrorMessage = "E-mail inválido.")]
        //public string email_pessoal { get; set; }


        [DisplayName("RG")]
        //[Required]
        public int rg { get; set; }

        [DisplayName("CPF")]
        // [Required]
        public int cpf { get; set; }

        [DisplayName("Telefone Pessoal")]
        public string telefone { get; set; }


        [DisplayName("NRE")]
        public NRECMT.NRE id_nre { get; set; }

        //[DisplayName("Município")]     //*************
        //public NRECMT.Municipio municipio { get; set; }        //***************

        //[DisplayName("Cargo/Função")]
        //public NRECMT.cargo_funcao cargo_funcao { get; set; }

        [DisplayName("E-mail Funcional")]
        [StringLength(50)]
        // [Required(ErrorMessage = "Informe o seu E-mail Funcional.")]
        // [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*", ErrorMessage = "E-mail inválido.")]
        public string email { get; set; }

        //[DisplayName("Telefone Funcional")]

        //public string telefone_funcional { get; set; }
        //// public DateTime CriadoEm { get; set; }

    }

    namespace NRECMT
    {
        public enum Municipio
        {
            Abatia = 1,
            Adrianopolis,
            Agudos_do_Sul,
            Almirante_Tamandare,
            Altamira_do_Parana,
            Altania,
            Alto_Parana,
            Alto_Piquiri,
            Alvorada_do_Sul,
            Amapora,
            Ampere,
            Anahy,
            Andira,
            Angulo,
            Antonina,
            Antonio_Olinto,
            Apucarana,
            Arapongas,
            Arapoti,
            Arapua,
            Araruna,
            Araucaria,
            Ariranha_do_Ivai,
            Assai,
            Assis_Chateaubriand,
            Astorga,
            Atalaia,
            Balsa_Nova,
            Bandeirantes,
            Barbosa_Ferraz,
            Barra_do_Jacare,
            Barracao,
            Bela_Vista_da_Caroba,
            Bela_Vista_do_Paraiso,
            Bituruna,
            Boa_Esperanca_do_Iguacu,
            Boa_Esperanca,
            Boa_Ventura_de_Sao_Roque,
            Boa_Vista_da_Aparecida,
            Bocaiuva_do_Sul,
            Bom_Jesus_do_Sul,
            Bom_Sucesso_do_Sul,
            Bom_Sucesso,
            Borrazopolis,
            Braganey,
            Brasilandia_do_Sul,
            Cafeara,
            Cafelandia,
            Cafezal_do_Sul,
            California,
            Cambara,
            Cambe,
            Cambira,
            Campina_Grande_do_Sul,
            Campina_da_Lagoa,
            Campina_do_Simao,
            Campo_Bonito,
            Campo_Largo,
            Campo_Magro,
            Campo_Mourao,
            Campo_do_Tenente,
            Candido_de_Abreu,
            Candoi,
            Cantagalo,
            Capanema,
            Capitao_Leonidas_Marques,
            Carambei,
            Carlopolis,
            Cascavel,
            Castro,
            Catanduvas,
            Centenario_do_Sul,
            Cerro_Azul,
            Ceu_Azul,
            Chopinzinho,
            Cianorte,
            Cidade_Gaucha,
            Clevelandia,
            Colombo,
            Colorado,
            Congonhinhas,
            Conselheiro_Mairinck,
            Contenda,
            Corbelia,
            Cornelio_Procopio,
            Coronel_Domingos_Soares,
            Coronel_Vivida,
            Corumbatai_do_Sul,
            Cruz_Machado,
            Cruzeiro_do_Iguacu,
            Cruzeiro_do_Oeste,
            Cruzeiro_do_Sul,
            Cruzmaltina,
            Curitiba,
            Curiuva,
            Diamante_dOeste,
            Diamante_do_Norte,
            Diamante_do_Sul,
            Dois_Vizinhos,
            Douradina,
            Doutor_Camargo,
            Doutor_Ulysses,
            Eneas_Marques,
            Engenheiro_Beltrao,
            Entre_Rios_do_Oeste,
            Esperanca_Nova,
            Espigao_Alto_do_Iguacu,
            Farol,
            Faxinal,
            Fazenda_Rio_Grande,
            Fenix,
            Fernandes_Pinheiro,
            Figueira,
            Flor_da_Serra_do_Sul,
            Florai,
            Floresta,
            Florestopolis,
            Florida,
            Formosa_do_Oeste,
            Foz_do_Iguacu,
            Foz_do_Jordao,
            Francisco_Alves,
            Francisco_Beltrao,
            General_Carneiro,
            Godoy_Moreira,
            Goioere,
            Goioxim,
            Grandes_Rios,
            Guaira,
            Guairaca,
            Guamiranga,
            Guapirama,
            Guaporema,
            Guaraci,
            Guaraniacu,
            Guarapuava,
            Guaraquecaba,
            Guaratuba,
            Honorio_Serpa,
            Ibaiti,
            Ibema,
            Ibipora,
            Icaraima,
            Iguaracu,
            Iguatu,
            Imbau,
            Imbituva,
            Inacio_Martins,
            Inaja,
            Indianopolis,
            Ipiranga,
            Ipora,
            Iracema_do_Oeste,
            Irati,
            Iretama,
            Itaguaje,
            Itaipulandia,
            Itambaraca,
            Itambe,
            Itapejara_dOeste,
            Itaperucu,
            Itauna_do_Sul,
            Ivai,
            Ivaipora,
            Ivate,
            Ivatuba,
            Jaboti,
            Jacarezinho,
            Jaguapita,
            Jaguariaiva,
            Jandaia_do_Sul,
            Janiopolis,
            Japira,
            Japura,
            Jardim_Alegre,
            Jardim_Olinda,
            Jataizinho,
            Jesuitas,
            Joaquim_Tavora,
            Jundiai_do_Sul,
            Juranda,
            Jussara,
            Kalore,
            Lapa,
            Laranjal,
            Laranjeiras_do_Sul,
            Leopolis,
            Lidianopolis,
            Lindoeste,
            Loanda,
            Lobato,
            Londrina,
            Luiziana,
            Lunardelli,
            Lupionopolis,
            Mallet,
            Mambore,
            Mandaguacu,
            Mandaguari,
            Mandirituba,
            Manfrinopolis,
            Mangueirinha,
            Manoel_Ribas,
            Marechal_Candido_Rondon,
            Maria_Helena,
            Marialva,
            Marilandia_do_Sul,
            Marilena,
            Mariluz,
            Maringa,
            Mariopolis,
            Maripa,
            Marmeleiro,
            Marquinho,
            Marumbi,
            Matelandia,
            Matinhos,
            Mato_Rico,
            Maua_da_Serra,
            Medianeira,
            Mercedes,
            Mirador,
            Miraselva,
            Missal,
            Moreira_Sales,
            Morretes,
            Munhoz_de_Melo,
            Nossa_Senhora_das_Gracas,
            Nova_Alianca_do_Ivai,
            Nova_America_da_Colina,
            Nova_Aurora,
            Nova_Cantu,
            Nova_Esperanca_do_Sudoeste,
            Nova_Esperanca,
            Nova_Fatima,
            Nova_Laranjeiras,
            Nova_Londrina,
            Nova_Olimpia,
            Nova_Prata_do_Iguacu,
            Nova_Santa_Barbara,
            Nova_Santa_Rosa,
            Nova_Tebas,
            Novo_Itacolomi,
            Ortigueira,
            Ourizona,
            Ouro_Verde_do_Oeste,
            Paicandu,
            Palmas,
            Palmeira,
            Palmital,
            Palotina,
            Paraiso_do_Norte,
            Paranacity,
            Paranagua,
            Paranapoema,
            Paranavai,
            Pato_Bragado,
            Pato_Branco,
            Paula_Freitas,
            Paulo_Frontin,
            Peabiru,
            Perobal,
            Perola_dOeste,
            Perola,
            Pien,
            Pinhais,
            Pinhal_de_Sao_Bento,
            Pinhalao,
            Pinhao,
            Pirai_do_Sul,
            Piraquara,
            Pitanga,
            Pitangueiras,
            Planaltina_do_Parana,
            Planalto,
            Ponta_Grossa,
            Pontal_do_Parana,
            Porecatu,
            Porto_Amazonas,
            Porto_Barreiro,
            Porto_Rico,
            Porto_Vitoria,
            Prado_Ferreira,
            Pranchita,
            Presidente_Castelo_Branco,
            Primeiro_de_Maio,
            Prudentopolis,
            Quarto_Centenario,
            Quatigua,
            Quatro_Barras,
            Quatro_Pontes,
            Quedas_do_Iguacu,
            Querencia_do_Norte,
            Quinta_do_Sol,
            Quitandinha,
            Ramilandia,
            Rancho_Alegre_dOeste,
            Rancho_Alegre,
            Realeza,
            Reboucas,
            Renascenca,
            Reserva_do_Iguacu,
            Reserva,
            Ribeirao_Claro,
            Ribeirao_do_Pinhal,
            Rio_Azul,
            Rio_Bom,
            Rio_Bonito_do_Iguacu,
            Rio_Branco_do_Ivai,
            Rio_Branco_do_Sul,
            Rio_Negro,
            Rolandia,
            Roncador,
            Rondon,
            Rosario_do_Ivai,
            Sabaudia,
            Salgado_Filho,
            Salto_do_Itarare,
            Salto_do_Lontra,
            Santa_Amelia,
            Santa_Cecilia_do_Pavao,
            Santa_Cruz_de_Monte_Castelo,
            Santa_Fe,
            Santa_Helena,
            Santa_Ines,
            Santa_Isabel_do_Ivai,
            Santa_Izabel_do_Oeste,
            Santa_Lucia,
            Santa_Maria_do_Oeste,
            Santa_Mariana,
            Santa_Monica,
            Santa_Tereza_do_Oeste,
            Santa_Terezinha_de_Itaipu,
            Santana_do_Itarare,
            Santo_Antonio_da_Platina,
            Santo_Antonio_do_Caiua,
            Santo_Antonio_do_Paraiso,
            Santo_Antonio_do_Sudoeste,
            Santo_Inacio,
            Sao_Carlos_do_Ivai,
            Sao_Jeronimo_da_Serra,
            Sao_Joao_do_Caiua,
            Sao_Joao_do_Ivai,
            Sao_Joao_do_Triunfo,
            Sao_Joao,
            Sao_Jorge_dOeste,
            Sao_Jorge_do_Ivai,
            Sao_Jorge_do_Patrocinio,
            Sao_Jose_da_Boa_Vista,
            Sao_Jose_das_Palmeiras,
            Sao_Jose_dos_Pinhais,
            Sao_Manoel_do_Parana,
            Sao_Mateus_do_Sul,
            Sao_Miguel_do_Iguacu,
            Sao_Pedro_do_Iguacu,
            Sao_Pedro_do_Ivai,
            Sao_Pedro_do_Parana,
            Sao_Sebastiao_da_Amoreira,
            Sao_Tome,
            Sapopema,
            Sarandi,
            Saudade_do_Iguacu,
            Senges,
            Serranopolis_do_Iguacu,
            Sertaneja,
            Sertanopolis,
            Siqueira_Campos,
            Sulina,
            Tamarana,
            Tamboara,
            Tapejara,
            Tapira,
            Teixeira_Soares,
            Telemaco_Borba,
            Terra_Boa,
            Terra_Rica,
            Terra_Roxa,
            Tibagi,
            Tijucas_do_Sul,
            Toledo,
            Tomazina,
            Tres_Barras_do_Parana,
            Tunas_do_Parana,
            Tuneiras_do_Oeste,
            Tupassi,
            Turvo,
            Ubirata,
            Umuarama,
            Uniao_da_Vitoria,
            Uniflor,
            Urai,
            Ventania,
            Vera_Cruz_do_Oeste,
            Vere,
            Vila_Alta,
            Virmond,
            Vitorino,
            Wenceslau_Braz,
            Xambre
        }

        public enum NRE
        {
            Apucarana = 6,
            Área_Metropolitana_Norte = 4,
            Área_Metropolitana_Sul = 5,
            Assis_Chateaubriand = 7,
            Campo_Mourão = 8,
            Cascavel = 9,
            Cianorte = 10,
            Cornélio_Procópio = 11,
            Curitiba = 12,
            Dois_Vizinhos = 13,
            Foz_do_Iguaçu = 14,
            Francisco_Beltrão = 15,
            Goioerê = 16,
            Guarapuava = 17,
            Ibaiti = 18,
            Irati = 19,
            Ivaiporã = 20,
            Jacarezinho = 21,
            Laranjeiras_do_Sul = 22,
            Loanda = 23,
            Londrina = 24,
            Maringá = 25,
            Paranaguá = 26,
            Paranavaí = 27,
            Pato_Branco = 28,
            Pitanga = 29,
            Ponta_Grossa = 30,
            Telêmaco_Borba = 31,
            Toledo = 32,
            Umuarama = 33,
            Wenceslau_Braz = 35,
            União_da_Vitória = 34
        }

        public enum cargo_funcao
        {
            Administrador = 1,
            Secretário_Municipal = 2,
            Servidor_Escola_Municipal = 3,
            Usuário_Comum_Consulta = 4

        }
    }

}

